# Generated by Django 2.0.2 on 2018-02-18 21:19

from django.db import migrations, models
import oai_pmh.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', oai_pmh.fields.SingleLineTextField(unique=True)),
                ('schema', models.URLField(max_length=2048)),
                ('namespace', models.URLField(max_length=2048)),
            ],
            options={
                'verbose_name': 'Metadata format',
                'verbose_name_plural': 'Metadata formats',
                'ordering': ('prefix',),
            },
        ),
    ]
