# Generated by Django 2.0.2 on 2018-02-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('prefix', models.TextField(unique=True, verbose_name='Prefix')),
                ('schema', models.URLField(max_length=2048, verbose_name='Schema')),
                ('namespace', models.URLField(max_length=2048, verbose_name='Namespace')),
            ],
            options={
                'verbose_name': 'Metadata format',
                'verbose_name_plural': 'Metadata formats',
                'ordering': ('prefix',),
            },
        ),
    ]
