# Generated by Django 2.0.2 on 2018-02-18 21:28

from django.db import migrations, models
import oai_pmh.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oai_pmh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spec', oai_pmh.fields.SingleLineTextField(unique=True)),
                ('name', oai_pmh.fields.SingleLineTextField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Set',
                'verbose_name_plural': 'Sets',
                'ordering': ('name',),
            },
        ),
    ]
