# Generated by Django 2.0.2 on 2018-02-18 21:32

from django.db import migrations, models
import oai_pmh.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oai_pmh', '0002_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', oai_pmh.fields.SingleLineTextField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('metadata_formats', models.ManyToManyField(blank=True, related_name='identifiers', to='oai_pmh.MetadataFormat')),
                ('sets', models.ManyToManyField(blank=True, related_name='headers', to='oai_pmh.Set')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'ordering': ('identifier',),
            },
        ),
    ]
