# Generated by Django 2.0.2 on 2018-02-18 21:36

from django.db import migrations, models
import django.db.models.deletion
import oai_pmh.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oai_pmh', '0003_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumptionToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField()),
                ('complete_list_size', models.IntegerField(default=0)),
                ('cursor', models.IntegerField(default=0)),
                ('token', oai_pmh.fields.SingleLineTextField(unique=True)),
                ('from_timestamp', models.DateTimeField(blank=True, null=True)),
                ('until_timestamp', models.DateTimeField(blank=True, null=True)),
                ('metadata_prefix', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oai_pmh.MetadataFormat')),
                ('set_spec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oai_pmh.Set')),
            ],
            options={
                'verbose_name': 'Resumption token',
                'verbose_name_plural': 'Resumption tokens',
                'ordering': ('expiration_date',),
            },
        ),
    ]
