# Generated by Django 2.0.2 on 2018-02-18 21:43

from django.db import migrations, models
import django.db.models.deletion
import oai_pmh.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oai_pmh', '0004_resumptiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('header', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oai_pmh.Header')),
                ('identifier', oai_pmh.fields.SingleLineTextField(verbose_name=' dc:identifier')),
                ('date', models.DateTimeField(auto_now=True, verbose_name=' dc:date')),
                ('title', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:title')),
                ('creator', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:creator')),
                ('subject', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:subject')),
                ('description', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:description')),
                ('publisher', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:publisher')),
                ('contributor', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:contributor')),
                ('type', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:type')),
                ('format', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:format')),
                ('source', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:source')),
                ('language', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:language')),
                ('relation', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:relation')),
                ('coverage', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:coverage')),
                ('rights', oai_pmh.fields.SingleLineTextField(blank=True, null=True, verbose_name=' dc:rights')),
            ],
            options={
                'verbose_name': 'Dublin Core record',
                'verbose_name_plural': 'Dublin Core records',
                'ordering': ('header',),
            },
        ),
    ]
