# Generated by Django 3.2.13 on 2022-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oai_pmh', '0006_xmlrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcrecord',
            name='date',
            field=models.TextField(verbose_name=' dc:date'),
        ),
    ]
