# Generated by Django 2.0.2 on 2018-02-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_oai_pmh', '0002_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('identifier', models.TextField(unique=True, verbose_name='Identifier')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('metadata_formats', models.ManyToManyField(blank=True, related_name='identifiers', to='django_oai_pmh.MetadataFormat', verbose_name='Metadata format')),
                ('sets', models.ManyToManyField(blank=True, related_name='headers', to='django_oai_pmh.Set', verbose_name='Set')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
                'ordering': ('identifier',),
            },
        ),
    ]
