# Copyright (C) 2018-2026 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of django_oai_pmh.
#
# django_oai_pmh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# django_oai_pmh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with django_oai_pmh. If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 3.1.8 on 2021-04-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("django_oai_pmh", "0005_oaidc_metadataformat"),
    ]

    operations = [
        migrations.CreateModel(
            name="XMLRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("xml_metadata", models.TextField(verbose_name="XML metadta")),
                (
                    "header",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xmlrecords",
                        to="django_oai_pmh.header",
                        verbose_name="Header",
                    ),
                ),
                (
                    "metadata_prefix",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="xmlrecords",
                        to="django_oai_pmh.metadataformat",
                        verbose_name="Metadata prefix",
                    ),
                ),
            ],
            options={
                "verbose_name": "XML record",
                "verbose_name_plural": "XML records",
                "ordering": ("header", "metadata_prefix"),
            },
        ),
    ]
