# Copyright (C) 2018-2026 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of django_oai_pmh.
#
# django_oai_pmh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# django_oai_pmh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with django_oai_pmh. If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 3.2.13 on 2022-05-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_oai_pmh", "0006_xmlrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcrecord",
            name="date",
            field=models.TextField(verbose_name=" dc:date"),
        ),
    ]
