# Copyright (C) 2018-2024 J. Nathanael Philipp (jnphilipp) <nathanael@philipp.land>
#
# This file is part of django_oai_pmh.
#
# django_oai_pmh is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# django_oai_pmh is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with django_oai_pmh. If not, see <http://www.gnu.org/licenses/>.
# Generated by Django 4.0.4 on 2022-05-17 07:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_oai_pmh", "0007_alter_dcrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dcrecord",
            name="contributor",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:contributor"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="coverage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:coverage"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="creator",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:creator"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="date",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:date"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="description",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:description"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="format",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:format"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="identifier",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:identifier"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="language",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:language"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="publisher",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:publisher"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="relation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:relation"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="rights",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:rights"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="source",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:source"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="subject",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:subject"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="title",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:title"),
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="dcrecord",
            name="type",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(verbose_name=" dc:type"),
                null=True,
                size=None,
            ),
        ),
    ]
